apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: default
  labels:
    autorollout.io: "true"
    app: my-app
type: Opaque
data:
  # Base64 encoded values
  # username = "admin" (base64: YWRtaW4=)
  # password = "secret123" (base64: c2VjcmV0MTIz)
  # api-key = "sk-1234567890abcdef" (base64: c2stMTIzNDU2Nzg5MGFiY2RlZg==)
  username: YWRtaW4=
  password: c2VjcmV0MTIz
  api-key: c2stMTIzNDU2Nzg5MGFiY2RlZg==
