apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-secret-env-vars
  namespace: default
  labels:
    app: app-secret-env-vars
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-secret-env-vars
  template:
    metadata:
      labels:
        app: app-secret-env-vars
    spec:
      containers:
        - name: app-container
          image: nginx:1.21
          ports:
            - containerPort: 8080
          # Individual environment variables from Secret
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: password
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: api-key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-secret-env-from
  namespace: default
  labels:
    app: app-secret-env-from
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-secret-env-from
  template:
    metadata:
      labels:
        app: app-secret-env-from
    spec:
      containers:
        - name: app-container
          image: nginx:1.21
          ports:
            - containerPort: 8080
          # All Secret keys as environment variables
          envFrom:
            - secretRef:
                name: app-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-secret-volume-mount
  namespace: default
  labels:
    app: app-secret-volume-mount
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-secret-volume-mount
  template:
    metadata:
      labels:
        app: app-secret-volume-mount
    spec:
      containers:
        - name: app-container
          image: nginx:1.21
          ports:
            - containerPort: 8080
          # Secret mounted as volume
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/secrets
              readOnly: true
      volumes:
        - name: secret-volume
          secret:
            secretName: app-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-image-pull-secret
  namespace: default
  labels:
    app: app-image-pull-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-image-pull-secret
  template:
    metadata:
      labels:
        app: app-image-pull-secret
    spec:
      # Using secret as imagePullSecret
      imagePullSecrets:
        - name: app-secret
      containers:
        - name: app-container
          image: nginx:1.21
          ports:
            - containerPort: 8080
